#include "rata.h"

Barrier *BARRIERS_HEAD = NULL;
Box *BOXS_HEAD = NULL;
Destination *DESTINATIONS_HEAD = NULL;
Bg *BG_HEAD = NULL;

PLAYER player;
int CURRENT_LEVEL = 1;
char MAP_PATH[] = "assets/levels/map0.txt";

int RUNNING = 1;
int IS_SOLVED = 0;

int SCREEN_WIDTH = 800;
int SCREEN_HEIGHT = 800;

int VERTICAL_BOXES_NUMBER;
int HORIZONTAL_BOXES_NUMBER;

int BLOCK_SIZE = 0;
int BG_SIZE = 200;

int DESTINATIONS_NUMBER;
int SOLVED_BOXES;
// SDL_Rect MAIN_SCREEN;

Mix_Chunk *MOVE_SOUND = NULL;
Mix_Chunk *NON_MOVE_SOUND = NULL;
Mix_Chunk *MOVE_BOX_SOUND = NULL;
Mix_Chunk *BOX_ON_PLACE_SOUND = NULL;
Mix_Chunk *BOX_NON_PLACE_SOUND = NULL;
Mix_Chunk *RESTART_SOUND = NULL;

SDL_Renderer *RENDERER = NULL;
SDL_Window *WINDOW = NULL;

SDL_Texture *DESTINATIONS_TEXTURE = NULL;
SDL_Texture *BACKGROUND_TEXTURE = NULL;
SDL_Texture *BARRIERS_TEXTURE = NULL;
SDL_Texture *PLAYER_TEXTURE = NULL;
SDL_Texture *PLAYER_UP_TEXTURE = NULL;
SDL_Texture *PLAYER_DOWN_TEXTURE = NULL;
SDL_Texture *BOX_TEXTURE = NULL;
SDL_Texture *LOGO_TEXTURE = NULL;
// SDL_Texture *INFO_TEXTURE = NULL;
